[workspace]
resolver = "2"
members = ["gm-proximity", "bench", "convert", "spatial"]
exclude = ["data/*"]

[workspace.package]
edition = "2024"
version = "0.2.0"

[workspace.dependencies]
anyhow = "1.0.97"
clap = { version = "^4.5", features = ["derive"] }
encoding_rs_io = "0.1"
geo = "^0.29"
geojson = { version = "^0.24", features = ["geo-types"] }
serde_json = "^1.0"
spatial = { path = "spatial" }

[profile.debug-release]
inherits = "release"
debug = true
