[workspace]
resolver = "2"
members = ["proximity-server", "proximity-client", "proximity-ipc", "proximity-bench", "convert", "spatial", "network", "protocol", "bench"]
exclude = ["data/*"]

[workspace.package]
edition = "2024"
version = "0.3.0"

[workspace.dependencies]
anyhow = "1.0.97"
clap = { version = "^4.5", features = ["derive"] }
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
encoding_rs_io = "0.1"
geo = "^0.29"
geojson = { version = "^0.24", features = ["geo-types"] }
network = { path = "network" }
protocol = { path = "protocol" }
proximity-ipc = { path = "proximity-ipc" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
serde_json = "^1.0"
spatial = { path = "spatial" }

[profile.debug-release]
inherits = "release"
debug = true
